#!/usr/bin/python3
"""Module that factorizes as many numbers as possible
into a product of two smaller numbers."""

import sys


def factorize(num: int):
    """
    Factorizes the given number into two smaller factors, if possible.
    Prints the factorization in the format "num=factor1*factor2".
    """
    itr = 2

    # Check if the number is less than 2, since we cannot factorize numbers less than 2
    if num < 2:
        return
    
    # Keep dividing the number by the iterator until it's no longer divisible
    while num % itr:
        itr += 1

    # Once the loop ends, itr should be a factor of num
    # We can print the factorization in the required format
    print("{}={}*{}".format(num, num//itr, itr))


if __name__ == "__main__":
    # Check if the script was called with the filename argument
    if len(sys.argv) != 2:
        sys.exit()

    try:
        with open(sys.argv[1]) as file:
            line = file.readline()

            while line != "":
                # Convert the line to an integer
                number = int(line.strip())
                # Factorize the number and print the result
                factorize(number)
                # Read the next line from the file
                line = file.readline()
    except Exception:
        pass
