#!/usr/bin/python3
'''
Factorize as many numbers as possible into a product of two smaller numbers.
'''
# Arguments library
import sys


# factorial number
def fac():
    '''
    function fac to search file to convert number and format n=p*q
    '''
    try:
        fhand = sys.argv[1]
        with open(fhand) as f:
            for fnum in f:
                fnum = int(fnum)
                if fnum % 2 == 0:
                        print("{}={}*{}".format(fnum, fnum // 2, 2))
                        continue
                x = 3
                while x < fnum // 2:
                    if fnum % x == 0:
                        print("{}={}*{}".format(fnum, fnum // x, x))
                        break
                    x = x + 2
                if x == (fnum // 2) + 1:
                    print("{}={}*{}".format(fnum, fnum, 1))
    except (IndexError):
        pass


# execute
fac()
